version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oneweek-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH_SECRET=changeme_random_string
      - GITHUB_ID=your_github_client_id
      - GITHUB_SECRET=your_github_client_secret
    # volumes:
    #   - ./.next/static:/app/.next/static
